### ISSUE TITLE
Project warnings

### ISSUE THREAD

**Issue by fryette** [jamesblasco/modal_bottom_sheet#115]
I fetched your project and see that some warnings exist, probably missed the super call here?

<img width="895" alt="Screen Shot 2020-11-20 at 11 01 58 AM" src="https://user-images.githubusercontent.com/3999503/99775123-d310b480-2b1f-11eb-899e-8c5121b075bd.png">

Also does master have any changes in comparison with the latest 1.0.1-dev package?

**Comment by jamesblasco** [comment]
This is from the example repo. RenderSliverGroup is not inside the package and it was part of a closed PR from the Flutter framework. I will probably remove it when I implement null-safety in the package.

1.0.0 fixes a breaking change in master due to null-safety changes. But it can be used inside earlier versions
