### ISSUE TITLE
Is this package being maintained?

### ISSUE THREAD

**Issue by aytunch** [jamesblasco/modal_bottom_sheet#222]
Hi @jamesblasco :)
I would like to know your status on `modal_bottom_sheet`
It is a widely used package but haven't been updated for the past year.
It would be helpful to know if this is going to be maintained for deciding on using it.

Thanks

**Comment by jamesblasco** [comment]
Hey! I am currently keeping very light maintenance to the project. 
First mainly because this last year is being quite difficult for me due to personal circumstances outside my control. 
Secondly I have been focused on a big refactor of the package that had been taking most of the time I have available to spend on this project. It is still a bit far to be ready but you can follow the progress here.https://github.com/jamesblasco/modal_bottom_sheet/tree/sheet

 I will make sure the current version package is maintained until the new one is released in the close future
