### ISSUE TITLE
Getting'_positions.isNotEmpty' Exception when programmatically scrolling inner scroll widget

### ISSUE THREAD

**Issue by basilmariano** [jamesblasco/modal_bottom_sheet#67]
when i try to programmatically scroll my inner scroll widget 

`mParentScrollController.animateTo(
        mParentScrollController.position.minScrollExtent,
        duration: Duration(milliseconds: 50),
        curve: Curves.linear);`

i get this fatal error when using the library. 

**mParentScrollController** is another scroll controller inside the BarModalBottomSheet that is added to a child scroll widget

**Comment by jamesblasco** [comment]
Can you share some code on when do you call this. The inner widget inside BarModalBottomSheet?

**Comment by emre88tosun** [comment]
Same for me, too. I just passed a plain ScrollController to a ListView in the showFloatingModalBottomSheet & showCustomModalBottomSheet.
ScrollController is initialized in the initState() and also disposed in the dispose().
Any suggestions would be appreciated.
Note:  I'm using 0.2.0 because of the VelocityTracker problem.

**Comment by jamesblasco** [comment]
Please, could you share some example code with the problem? It will be easier for me to debug the error and fix it

**Comment by antoniocasero** [comment]
I had the same issue and it is solved in the 0.2.0+1 version. (pre velocity tracker 2d4e8d3ce0eb3c34387f7239c29a0aaf59d29a3f )
