### ISSUE TITLE
Getter not found : opaque

### ISSUE THREAD

**Issue by NiranjanShah** [jamesblasco/modal_bottom_sheet#98]
Got below error when running the application on the Web.

 Error: Getter not found:
'opaque'.
        assert(opaque),                                                 

Flutter 1.24.0-4.0.pre.82 • channel master • https://github.com/flutter/flutter.git
Framework • revision e5814756a2 (3 hours ago) • 2020-10-27 01:47:03 -0700
Engine • revision 1857470267
Tools • Dart 2.11.0 (build 2.11.0-260.0.dev)

**Comment by LefebvreIlyas** [comment]
Hello @NiranjanShah, @jamesblasco 

`assert(opaque)` is placed in an initializer in the `modal_bottom_sheet` package but it is placed in the body of the constructor in the `Flutter` framework, It is this subtlety that causes the error. Because `The instance '...' member can't be accessed in an initializer`. Moreover as `assert(opaque)` is already present in the `Flutter` framework, there is no need to add it in the `modal_bottom_sheet` package.

Here is the Flutter code.

```dart
  MaterialPageRoute({
    required this.builder,
    RouteSettings? settings,
    this.maintainState = true,
    bool fullscreenDialog = false,
  }) : assert(builder != null),
       assert(maintainState != null),
       assert(fullscreenDialog != null),
       super(settings: settings, fullscreenDialog: fullscreenDialog) {
    assert(opaque);
  }
```

**Comment by LefebvreIlyas** [comment]
![image](https://user-images.githubusercontent.com/39876339/97312241-8e1d9900-1865-11eb-9365-246c72bc632f.png)

**Comment by jamesblasco** [comment]
This is solved now in  1.0.1-dev

**Comment by jinfagang** [comment]
@jamesblasco  Did u published to pub.dev?

**Comment by jamesblasco** [comment]
Yes but it is a pre-released version
https://pub.dev/packages/modal_bottom_sheet/versions/1.0.1-dev
